# Data Manipulation with Pandas

Pandas is the most widely used library of python for data science. It is incredibly helpful in manipulating the data so that you can derive better insights and build great machine learning models.

In this notebook, we will have a look at some of the intermediate concepts of working with pandas.


## Table of Contents

 - Apply function

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\esha.varma\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\esha.varma\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\esha.varma\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\esha.varma\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\esha.varma\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\esha.varma\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
### Loading dataset

import pandas as pd
import numpy as np

# read the dataset
data_BM = pd.read_csv('bigmart_data.csv')
# drop the null values
data_BM = data_BM.dropna(how="any")
# reset index after dropping
data_BM = data_BM.reset_index(drop=True)
# view the top results
data_BM.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
4,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088

### Apply function

- Apply function can be used to perform pre-processing/data-manipulation on your data both row wise and column wise.
- It is a faster method than simply using a **for** loop over your dataframe.
- Almost every time I need to iterate over a dataframe or it's rows/columns, I will think of using the `apply`.
- Hence, it is widely used in feature engineering code.

In [3]:
# accessing row wise
data_BM.apply(lambda x: x)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
4,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
...,...,...,...,...,...,...,...,...,...,...,...,...
4645,FDF53,20.750,reg,0.083607,Frozen Foods,178.8318,OUT046,1997,Small,Tier 1,Supermarket Type1,3608.6360
4646,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
4647,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
4648,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
4649,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [4]:
# access first row
data_BM.apply(lambda x: x[0])

Item_Identifier                          FDA15
Item_Weight                                9.3
Item_Fat_Content                       Low Fat
Item_Visibility                       0.016047
Item_Type                                Dairy
Item_MRP                              249.8092
Outlet_Identifier                       OUT049
Outlet_Establishment_Year                 1999
Outlet_Size                             Medium
Outlet_Location_Type                    Tier 1
Outlet_Type                  Supermarket Type1
Item_Outlet_Sales                     3735.138
dtype: object

In [5]:
# accessing column wise
data_BM.apply(lambda x: x, axis=1)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
4,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
...,...,...,...,...,...,...,...,...,...,...,...,...
4645,FDF53,20.750,reg,0.083607,Frozen Foods,178.8318,OUT046,1997,Small,Tier 1,Supermarket Type1,3608.6360
4646,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
4647,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
4648,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
4649,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [6]:
# access first column by index
data_BM.apply(lambda x: x[0], axis=1)

C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1670984150.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data_BM.apply(lambda x: x[0], axis=1)

0       FDA15
1       DRC01
2       FDN15
3       NCD19
4       FDP36
        ...
4645    FDF53
4646    FDF22
4647    NCJ29
4648    FDN46
4649    DRG01
Length: 4650, dtype: object

In [7]:
# access by column name
data_BM.apply(lambda x: x["Item_Fat_Content"], axis=1)

0       Low Fat
1       Regular
2       Low Fat
3       Low Fat
4       Regular
         ...
4645        reg
4646    Low Fat
4647    Low Fat
4648    Regular
4649    Low Fat
Length: 4650, dtype: object

- You can also use `apply` to implement a **condition** individually on every row/column of your dataframe.
- Suppose you want to clip Item_MRP to 200 and not consider any value greater than that.
```python
def clip_price(price):
    if price > 200:
        price = 200
    return price
```

In [8]:
# before clipping
data_BM["Item_MRP"][:5]

0    249.8092
1     48.2692
2    141.6180
3     53.8614
4     51.4008
Name: Item_MRP, dtype: float64

In [9]:
# clip price if it is greater than 200
def clip_price(price):
    if price > 200:
        price = 200
    return price

# after clipping
data_BM["Item_MRP"].apply(lambda x: clip_price(x))[:5]

0    200.0000
1     48.2692
2    141.6180
3     53.8614
4     51.4008
Name: Item_MRP, dtype: float64

- Suppose you want to label encode Outlet_Location_Type as 0, 1 and 2 for Tier 1, Tier 2 and Tier 3 city, your logic would be:

```python
def label_encode(city):
    if city == 'Tier 1':
        label = 0
    elif city == 'Tier 2':
        label = 1
    else:
        label = 2
    return label
```
- You can use the `apply` to operate `label_encode` logic on every row of the Outlet_Location_Type column.

In [10]:

# before label encoding
data_BM["Outlet_Location_Type"][:5]
# label encode city type
def label_encode(city):
    if city == 'Tier 1':
        label = 0
    elif city == 'Tier 2':
        label = 1
    else:
        label = 2
    return label

# operate label_encode on every row of Outlet_Location_Type
data_BM["Outlet_Location_Type"] = data_BM["Outlet_Location_Type"].apply(label_encode)

In [11]:
# after label encoding
data_BM["Outlet_Location_Type"][:5]

0    0
1    2
2    0
3    2
4    2
Name: Outlet_Location_Type, dtype: int64

# Data Manipulation with Pandas

In [12]:

### Loading dataset
import pandas as pd
import numpy as np

# read the dataset
data_BM = pd.read_csv('bigmart_data.csv')
# drop the null values
data_BM = data_BM.dropna(how="any")
# reset index after dropping
data_BM = data_BM.reset_index(drop=True)
# view the top results
data_BM.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
4,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088

### 1. Aggregating data

There are multiple functions that can be used to perform useful aggregations on data in pandas:

 - groupby
 - crosstab
 - pivottable


#### a. **What is the mean price for each item type?** : groupby
- In the given data set, I want to find out **what is the mean price for each item type**?
- You can use **groupby()** to achieve this.
- The first step would be to group the data by Item_Type column.

In [13]:

# group price based on item type
price_by_item = data_BM.groupby('Item_Type')

# display first few rows
price_by_item.first()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Item_Type,,,,,,,,,,,
Baking Goods,FDP36,10.395,Regular,0.000000,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
Breads,FDW11,12.600,Low Fat,0.048981,61.9194,OUT018,2009,Medium,Tier 3,Supermarket Type2,619.1940
Breakfast,FDP49,9.000,Regular,0.069089,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192
Canned,FDC02,21.350,Low Fat,0.069103,259.9278,OUT018,2009,Medium,Tier 3,Supermarket Type2,6768.5228
Dairy,FDA15,9.300,Low Fat,0.016047,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
Frozen Foods,FDR28,13.850,Regular,0.025896,165.0210,OUT046,1997,Small,Tier 1,Supermarket Type1,4078.0250
Fruits and Vegetables,FDY07,11.800,Low Fat,0.000000,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266
Hard Drinks,DRJ59,11.650,low fat,0.019356,39.1164,OUT013,1987,High,Tier 3,Supermarket Type1,308.9312
Health and Hygiene,NCB42,11.800,Low Fat,0.008596,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888
Household,NCD19,8.930,Low Fat,0.000000,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
Meat,FDN15,17.500,Low Fat,0.016760,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
Others,NCM43,14.500,Low Fat,0.019472,164.8210,OUT035,2004,Small,Tier 2,Supermarket Type1,2120.5730
Seafood,FDH21,10.395,Low Fat,0.031274,160.0604,OUT049,1999,Medium,Tier 1,Supermarket Type1,1267.6832
Snack Foods,FDO10,13.650,Regular,0.012741,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
Soft Drinks,DRC01,5.920,Regular,0.019278,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
Starchy Foods,FDB11,16.000,Low Fat,0.060837,226.8404,OUT035,2004,Small,Tier 2,Supermarket Type1,6301.1312

- Now that you have grouped by Item_Type, the next step would be to calculate the mean of Item_MRP.

In [14]:

# mean price by item 
price_by_item.Item_MRP.mean()

Item_Type
Baking Goods             125.795653
Breads                   141.300639
Breakfast                134.090683
Canned                   138.551179
Dairy                    149.481471
Frozen Foods             140.095830
Fruits and Vegetables    145.418257
Hard Drinks              140.102908
Health and Hygiene       131.437324
Household                149.884244
Meat                     140.279344
Others                   137.640870
Seafood                  146.595782
Snack Foods              147.569955
Soft Drinks              130.910182
Starchy Foods            151.256747
Name: Item_MRP, dtype: float64

- You can use `groupby` with **multiple** columns of the dataset too. 
- In this case, if you want to group first based on the Item_Type and then Item_MRP you can simply pass a list of column names.

In [15]:
# group on multiple columns
multiple_groups = data_BM[:10].groupby(['Item_Type', 'Item_Fat_Content'])
multiple_groups.first()

                                       Item_Identifier  Item_Weight  \
Item_Type             Item_Fat_Content
Baking Goods          Regular                    FDP36       10.395
Dairy                 Low Fat                    FDA15        9.300
                      Regular                    FDA03       18.500
Fruits and Vegetables Low Fat                    FDY07       11.800
                      Regular                    FDX32       15.100
Household             Low Fat                    NCD19        8.930
Meat                  Low Fat                    FDN15       17.500
Snack Foods           Regular                    FDO10       13.650
Soft Drinks           Regular                    DRC01        5.920

                                        Item_Visibility  Item_MRP  \
Item_Type             Item_Fat_Content
Baking Goods          Regular                  0.000000   51.4008
Dairy                 Low Fat                  0.016047  249.8092
                      Regular                  0.045464  144.1102
Fruits and Vegetables Low Fat                  0.000000   45.5402
                      Regular                  0.100014  145.4786
Household             Low Fat                  0.000000   53.8614
Meat                  Low Fat                  0.016760  141.6180
Snack Foods           Regular                  0.012741   57.6588
Soft Drinks           Regular                  0.019278   48.2692

                                       Outlet_Identifier  \
Item_Type             Item_Fat_Content
Baking Goods          Regular                     OUT018
Dairy                 Low Fat                     OUT049
                      Regular                     OUT046
Fruits and Vegetables Low Fat                     OUT049
                      Regular                     OUT049
Household             Low Fat                     OUT013
Meat                  Low Fat                     OUT049
Snack Foods           Regular                     OUT013
Soft Drinks           Regular                     OUT018

                                        Outlet_Establishment_Year Outlet_Size  \
Item_Type             Item_Fat_Content
Baking Goods          Regular                                2009      Medium
Dairy                 Low Fat                                1999      Medium
                      Regular                                1997       Small
Fruits and Vegetables Low Fat                                1999      Medium
                      Regular                                1999      Medium
Household             Low Fat                                1987        High
Meat                  Low Fat                                1999      Medium
Snack Foods           Regular                                1987        High
Soft Drinks           Regular                                2009      Medium

                                       Outlet_Location_Type  \
Item_Type             Item_Fat_Content
Baking Goods          Regular                        Tier 3
Dairy                 Low Fat                        Tier 1
                      Regular                        Tier 1
Fruits and Vegetables Low Fat                        Tier 1
                      Regular                        Tier 1
Household             Low Fat                        Tier 3
Meat                  Low Fat                        Tier 1
Snack Foods           Regular                        Tier 3
Soft Drinks           Regular                        Tier 3

                                              Outlet_Type  Item_Outlet_Sales
Item_Type             Item_Fat_Content
Baking Goods          Regular           Supermarket Type2           556.6088
Dairy                 Low Fat           Supermarket Type1          3735.1380
                      Regular           Supermarket Type1          2187.1530
Fruits and Vegetables Low Fat           Supermarket Type1          1516.0266
                      Regular           Supermarket Type1          1589.2646
Household             Low Fat           Supermarket Type1           994.7052
Meat                  Low Fat           Supermarket Type1          2097.2700
Snack Foods           Regular           Supermarket Type1           343.5528
Soft Drinks           Regular           Supermarket Type2           443.4228

#### b. **How are outlet sizes distributed based on the city type?** : crosstab

- This function is used to get an initial “feel” (view) of the data. Here, we can validate some basic hypothesis.
- For example, in this case, "Outlet_Location_Type" is expected to affect the "Outlet_Size" significantly. This can be tested using cross-tabulation as shown below:

In [16]:
# generate crosstab of Outlet_Size and Outlet_Location_Type
pd.crosstab(data_BM["Outlet_Size"],data_BM["Outlet_Location_Type"],margins=True)

Outlet_Location_Type  Tier 1  Tier 2  Tier 3   All
Outlet_Size
High                       0       0     932   932
Medium                   930       0     928  1858
Small                    930     930       0  1860
All                     1860     930    1860  4650

- If you notice in the above `crosstab` there are interesting insights like 50% of medium size outlets are present only in either Tier 1 or Tier 2 cities.
- Another counter intuitive thing to notice is that high outlet size is only present in Tier 3 city though general assumption would be towards Tier 1 cities having larger outlet sizes.




#### c. How are the sales changing per year? : pivottable

- Pandas can be used to create MS Excel style pivot tables.
- The fun thing about pandas `pivot_table` is you can get another point of view on your data with only one line of code. 
- Most of the `pivot_table` parameters use default values, so the only mandatory parameters you must add are `data` and `index`. 
    - **data** is self explanatory – it’s the DataFrame you’d like to use
    - **index** is the column, grouper, array (or list of the previous) you’d like to group your data by. 
    - **values (optional)** is the column you’d like to aggregate. If you do not specify this then the function will aggregate all numeric columns.

In [17]:

# create pivot table
pd.pivot_table(data_BM, index=['Outlet_Establishment_Year'], values= "Item_Outlet_Sales")

                           Item_Outlet_Sales
Outlet_Establishment_Year
1987                             2298.995256
1997                             2277.844267
1999                             2348.354635
2004                             2438.841866
2009                             1995.498739



- In the above example, the mean sales for each year is shown.
- You can also pass multiple columns to pivot table, in the next exammple we try to see mean sales not just by the year but also taking into account the **outlet size** and type of the city.

In [18]:
# create pivot table
pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales")

                                                            Item_Outlet_Sales
Outlet_Establishment_Year Outlet_Location_Type Outlet_Size
1987                      Tier 3               High               2298.995256
1997                      Tier 1               Small              2277.844267
1999                      Tier 1               Medium             2348.354635
2004                      Tier 2               Small              2438.841866
2009                      Tier 3               Medium             1995.498739

- This makes it easier to see that Tier 1 cities have good sales irrespective of year and outlet size.
- We also notice that Tier 2 and Tier 3 cities dominate during the later years. This might mean both they are performing better or we have less data of later years.
- You can also perform multiple aggregations like mean, median, min, max etc. in a pivot table by using **aggfunc** parameter.

In [19]:
pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])

C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <function mean at 0x000001FF1D486D40> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])
C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <function median at 0x000001FF1D5D8AE0> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])
C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <built-in function min> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])
C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])
C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <function std at 0x000001FF1D486E80> is currently using DataFrameGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])

,,,mean,median,min,max,std
,,,Item_Outlet_Sales,Item_Outlet_Sales,Item_Outlet_Sales,Item_Outlet_Sales,Item_Outlet_Sales
Outlet_Establishment_Year,Outlet_Location_Type,Outlet_Size,,,,,
1987,Tier 3,High,2298.995256,2050.6640,73.2380,10256.6490,1533.531664
1997,Tier 1,Small,2277.844267,1945.8005,101.8674,9779.9362,1488.405631
1999,Tier 1,Medium,2348.354635,1966.1074,111.8544,7646.0472,1513.289464
2004,Tier 2,Small,2438.841866,2109.2544,113.8518,8479.6288,1538.512533
2009,Tier 3,Medium,1995.498739,1655.1788,69.2432,6768.5228,1375.932889

to see mean sales not just by the year but also taking into account the **outlet size** and type of the city.
# create pivot table

In [20]:
pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales")

                                                            Item_Outlet_Sales
Outlet_Establishment_Year Outlet_Location_Type Outlet_Size
1987                      Tier 3               High               2298.995256
1997                      Tier 1               Small              2277.844267
1999                      Tier 1               Medium             2348.354635
2004                      Tier 2               Small              2438.841866
2009                      Tier 3               Medium             1995.498739

- This makes it easier to see that Tier 1 cities have good sales irrespective of year and outlet size.
- We also notice that Tier 2 and Tier 3 cities dominate during the later years. This might mean both they are performing better or we have less data of later years.
- You can also perform multiple aggregations like mean, median, min, max etc. in a pivot table by using **aggfunc** parameter.

In [21]:
pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])

C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <function mean at 0x000001FF1D486D40> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])
C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <function median at 0x000001FF1D5D8AE0> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])
C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <built-in function min> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])
C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])
C:\Users\esha.varma\AppData\Local\Temp\ipykernel_5520\1353089848.py:1: FutureWarning: The provided callable <function std at 0x000001FF1D486E80> is currently using DataFrameGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  pd.pivot_table(data_BM, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values= "Item_Outlet_Sales", aggfunc= [np.mean, np.median, min, max, np.std])

,,,mean,median,min,max,std
,,,Item_Outlet_Sales,Item_Outlet_Sales,Item_Outlet_Sales,Item_Outlet_Sales,Item_Outlet_Sales
Outlet_Establishment_Year,Outlet_Location_Type,Outlet_Size,,,,,
1987,Tier 3,High,2298.995256,2050.6640,73.2380,10256.6490,1533.531664
1997,Tier 1,Small,2277.844267,1945.8005,101.8674,9779.9362,1488.405631
1999,Tier 1,Medium,2348.354635,1966.1074,111.8544,7646.0472,1513.289464
2004,Tier 2,Small,2438.841866,2109.2544,113.8518,8479.6288,1538.512533
2009,Tier 3,Medium,1995.498739,1655.1788,69.2432,6768.5228,1375.932889

# Data Manipulation with Pandas


Pandas is the most widely used library of python for data science. It is incredibly helpful in manipulating the data so that you can derive better insights and build great machine learning models.

In this notebook, we will have a look at some of the intermediate concepts of working with pandas.


## Table of Contents

1. Sorting dataframes
2. Merging dataframes

### Loading dataset

In [22]:
import pandas as pd
import numpy as np

# read the dataset
data_BM = pd.read_csv('bigmart_data.csv')
# drop the null values
data_BM = data_BM.dropna(how="any")
# view the top results
data_BM.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088

### 1. Sorting dataframes

Pandas data frame has two useful functions

- **sort_values()**: to sort pandas data frame by one or more columns
- **sort_index()**: to sort pandas data frame by row index

Each of these functions come with numerous options, like sorting the data frame in specific order (ascending or descending), sorting in place, sorting with missing values, sorting by specific algorithm etc.

Suppose you want to sort the dataframe by "Outlet_Establishment_Year" then you will use **sort_values**

In [23]:
# sort by year
sorted_data = data_BM.sort_values(by='Outlet_Establishment_Year')
# print sorted data
sorted_data[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
44,FDL50,12.150,Regular,0.042278,Canned,126.5046,OUT013,1987,High,Tier 3,Supermarket Type1,373.5138
41,FDK43,9.800,Low Fat,0.026818,Meat,126.0020,OUT013,1987,High,Tier 3,Supermarket Type1,2150.5340
71,FDL12,15.850,Regular,0.121532,Baking Goods,59.2220,OUT013,1987,High,Tier 3,Supermarket Type1,599.2200
8484,DRJ49,6.865,Low Fat,0.000000,Soft Drinks,129.9652,OUT013,1987,High,Tier 3,Supermarket Type1,2324.9736
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528

- Now `sort_values` takes multiple options like:
    - `ascending`: The default sorting order is ascending, when you pass False here then it sorts in descending order.
    - `inplace`: whether to do inplace sorting or not

In [24]:
# sort in place and descending order
data_BM.sort_values(by='Outlet_Establishment_Year', ascending=False, inplace=True)
data_BM[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
8521,FDN46,7.21,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8516,NCJ19,18.60,Low Fat,0.118661,Others,58.7588,OUT018,2009,Medium,Tier 3,Supermarket Type2,858.8820
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
8515,FDH24,20.70,Low Fat,0.021518,Baking Goods,157.5288,OUT018,2009,Medium,Tier 3,Supermarket Type2,1571.2880
8482,FDZ28,20.00,Regular,0.051702,Frozen Foods,125.8678,OUT018,2009,Medium,Tier 3,Supermarket Type2,763.0068

You might want to sort a data frame based on the values of multiple columns. 
We can specify the columns we want to sort by as a list in the argument for sort_values().

In [25]:

# read the dataset
data_BM = pd.read_csv('bigmart_data.csv')
# drop the null values
data_BM = data_BM.dropna(how="any")

# sort by multiple columns
data_BM.sort_values(by=['Outlet_Establishment_Year', 'Item_Outlet_Sales'], ascending=False)[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
43,FDC02,21.35,Low Fat,0.069103,Canned,259.9278,OUT018,2009,Medium,Tier 3,Supermarket Type2,6768.5228
2803,FDU51,20.20,Regular,0.096907,Meat,175.5028,OUT018,2009,Medium,Tier 3,Supermarket Type2,6729.9064
641,FDY51,12.50,Low Fat,0.081465,Meat,220.7798,OUT018,2009,Medium,Tier 3,Supermarket Type2,6611.3940
2282,NCX30,16.70,Low Fat,0.026729,Household,248.4776,OUT018,2009,Medium,Tier 3,Supermarket Type2,6439.6176
2887,FDR25,17.00,Regular,0.140090,Canned,265.1884,OUT018,2009,Medium,Tier 3,Supermarket Type2,6359.7216

- Note that when sorting by multiple columns, pandas sort_value() uses the first variable first and second variable next. 
- We can see the difference by switching the order of column names in the list.

In [26]:
# changed the order of columns
data_BM.sort_values(by=['Item_Outlet_Sales', 'Outlet_Establishment_Year'], ascending=False, inplace=True)
data_BM[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
4888,FDF39,14.850,Regular,0.019495,Dairy,261.2910,OUT013,1987,High,Tier 3,Supermarket Type1,10256.6490
4289,NCM05,6.825,Low Fat,0.059847,Health and Hygiene,262.5226,OUT046,1997,Small,Tier 1,Supermarket Type1,9779.9362
6409,FDA21,13.650,Low Fat,0.035931,Snack Foods,184.4924,OUT013,1987,High,Tier 3,Supermarket Type1,9069.5276
4991,NCQ53,17.600,Low Fat,0.018905,Health and Hygiene,234.6590,OUT046,1997,Small,Tier 1,Supermarket Type1,8508.9240
5752,FDI15,13.800,Low Fat,0.141326,Dairy,265.0884,OUT035,2004,Small,Tier 2,Supermarket Type1,8479.6288

- We can use **sort_index()** to sort pandas dataframe to sort by row index or names. 
- In this example, row index are numbers and in the earlier example we sorted data frame by 'Item_Outlet_Sales', 'Outlet_Establishment_Year' and therefore the row index are jumbled up. 
- We can sort by row index (with inplace=True option) and retrieve the original dataframe.

In [27]:
# sort by index
data_BM.sort_index(inplace=True)
data_BM[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088

### 2. Merging dataframes

- Joining and merging DataFrames is the core process to start with data analysis and machine learning tasks. 
- It is one of the toolkits which every Data Analyst or Data Scientist should master because in almost all the cases data comes from multiple source and files.
- Pandas has two useful functions for merging dataframes:
    - **concat()**
    - **merge()**

In [28]:
    
#### Creating dummy data
# create dummy data
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])
 

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['C4', 'C5', 'C6', 'C7'],
                     'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])
 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                     'B': ['B8', 'B9', 'B10', 'B11'],
                     'C': ['C8', 'C9', 'C10', 'C11'],
                     'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8, 9, 10, 11])

### a. concat() for combining dataframes
- Suppose you have the following three dataframes: df1, df2 and df3 and you want to combine them **"row-wise"** so that they become a single dataframe like the given image:
![](concat_1_a.png)
- You can use **concat()** here. You will have to pass the names of the DataFrames in a list as the argument to the concat().

In [29]:
# combine dataframes
result = pd.concat([df1, df2, df3])
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

- pandas also provides you with an option to label the DataFrames, after the concatenation, with a key so that you may know which data came from which DataFrame.
- You can achieve the same by passing additional argument **keys** specifying the label names of the DataFrames in a list.

In [30]:
# combine dataframes
result = pd.concat([df1, df2, df3], keys=['x', 'y', 'z'])
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11

- Mentioning the keys also makes it easy to retrieve data corresponding to a particular DataFrame. 
- You can retrieve the data of DataFrame df2 which had the label `y` by using the `loc` method.

In [31]:
# get second dataframe
result.loc['y']

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

- When gluing together multiple DataFrames, you have a choice of how to handle the other axes (other than the one being concatenated). This can be done in the following three ways:

    - Take the union of them all, `join='outer'`. This is the default option as it results in zero information loss.
    - Take the intersection, `join='inner'`.
    - Use a specific index, as passed to the `join_axes` argument.

- Here is an example of each of these methods. First, the default `join='outer'` behavior:

In [32]:

df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                        'D': ['D2', 'D3', 'D6', 'D7'],
                        'F': ['F2', 'F3', 'F6', 'F7']},
                       index=[2, 3, 6, 7])
    

result = pd.concat([df1, df4], axis=1, sort=False)
result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

- Here is the same thing with `join='inner'`:

In [33]:

result = pd.concat([df1, df4], axis=1, join='inner')
result

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

- Lastly, suppose we just wanted to `reuse the exact index` from the original DataFrame:

In [68]:
result = pd.concat([df1, df4], axis=1, join_axes =[df1.index])
result

TypeError: concat() got an unexpected keyword argument 'join_axes'

### b. merge() for combining dataframes using SQL like joins

- Another ubiquitous operation related to DataFrames is the merging operation. 
- Two DataFrames might hold different kinds of information about the same entity and linked by some common feature/column.
- We can use **merge()** to combine such dataframes in pandas.


#### Creating dummy data

In [40]:
# create dummy data
df_a = pd.DataFrame({
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']})

df_b = pd.DataFrame({
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']})

df_c = pd.DataFrame({
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]})

Now these are our dataframes:


- Let's start with a basic join, we want to combine `df_a` with `df_c` based on the `subject_id` column.

In [41]:
pd.merge(df_a, df_c, on='subject_id')

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          5     Ayoung   Atiches       16

- Now that we have done a basic join, let's get into **some commmon SQL joins.**

#### Merge with outer join

- “Full outer join produces the set of all records in Table A and Table B, with matching records from both sides where available. If there is no match, the missing side will contain null.”

In [42]:


pd.merge(df_a, df_b, on='subject_id', how='outer')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black
5          6          NaN         NaN         Bran     Balwner
6          7          NaN         NaN        Bryce       Brice
7          8          NaN         NaN        Betty      Btisan

#### Merge with inner join


- “Inner join produces only the set of records that match in both Table A and Table B.”

In [43]:

pd.merge(df_a, df_b, on='subject_id', how='inner')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

#### Merge with right join


- “Right outer join produces a complete set of records from Table B, with the matching records (where available) in Table A. If there is no match, the left side will contain null.”

In [44]:

pd.merge(df_a, df_b, on='subject_id', how='right')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black
2          6          NaN         NaN         Bran     Balwner
3          7          NaN         NaN        Bryce       Brice
4          8          NaN         NaN        Betty      Btisan

#### Merge with left join


- “Left outer join produces a complete set of records from Table A, with the matching records (where available) in Table B. If there is no match, the right side will contain null.”

In [45]:

pd.merge(df_a, df_b, on='subject_id', how='left')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black

### Merge OR Concat : Which to use when?

1. After learning both of the functions in detail, chances are that you might be confused which to use when. 
2. One major difference is that `merge()` is used to combine dataframes on the basis of values of **common columns**. While`concat()` is used to **append dataframes** one below the other (or sideways, depending on whether the axis option is set to 0 or 1).
3. Exact usage depends upon the kind of data you have and analysis you want to perform.

In [46]:
import pandas as pd
import numpy as np

# read the dataset
data_BM = pd.read_csv('bigmart_data.csv')
# drop the null values
data_BM = data_BM.dropna(how="any")
# view the top results
data_BM.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088

### 1. Sorting dataframes

Pandas data frame has two useful functions

- **sort_values()**: to sort pandas data frame by one or more columns
- **sort_index()**: to sort pandas data frame by row index

Each of these functions come with numerous options, like sorting the data frame in specific order (ascending or descending), sorting in place, sorting with missing values, sorting by specific algorithm etc.

Suppose you want to sort the dataframe by "Outlet_Establishment_Year" then you will use **sort_values**

In [48]:
# sort by year
sorted_data = data_BM.sort_values(by='Outlet_Establishment_Year')
# print sorted data
sorted_data[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
44,FDL50,12.150,Regular,0.042278,Canned,126.5046,OUT013,1987,High,Tier 3,Supermarket Type1,373.5138
41,FDK43,9.800,Low Fat,0.026818,Meat,126.0020,OUT013,1987,High,Tier 3,Supermarket Type1,2150.5340
71,FDL12,15.850,Regular,0.121532,Baking Goods,59.2220,OUT013,1987,High,Tier 3,Supermarket Type1,599.2200
8484,DRJ49,6.865,Low Fat,0.000000,Soft Drinks,129.9652,OUT013,1987,High,Tier 3,Supermarket Type1,2324.9736
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528

- Now `sort_values` takes multiple options like:
    - `ascending`: The default sorting order is ascending, when you pass False here then it sorts in descending order.
    - `inplace`: whether to do inplace sorting or not

In [49]:

# sort in place and descending order
data_BM.sort_values(by='Outlet_Establishment_Year', ascending=False, inplace=True)
data_BM[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
8521,FDN46,7.21,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8516,NCJ19,18.60,Low Fat,0.118661,Others,58.7588,OUT018,2009,Medium,Tier 3,Supermarket Type2,858.8820
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
8515,FDH24,20.70,Low Fat,0.021518,Baking Goods,157.5288,OUT018,2009,Medium,Tier 3,Supermarket Type2,1571.2880
8482,FDZ28,20.00,Regular,0.051702,Frozen Foods,125.8678,OUT018,2009,Medium,Tier 3,Supermarket Type2,763.0068

You might want to sort a data frame based on the values of multiple columns. 
We can specify the columns we want to sort by as a list in the argument for sort_values().

In [50]:

# read the dataset
data_BM = pd.read_csv('bigmart_data.csv')
# drop the null values
data_BM = data_BM.dropna(how="any")

# sort by multiple columns
data_BM.sort_values(by=['Outlet_Establishment_Year', 'Item_Outlet_Sales'], ascending=False)[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
43,FDC02,21.35,Low Fat,0.069103,Canned,259.9278,OUT018,2009,Medium,Tier 3,Supermarket Type2,6768.5228
2803,FDU51,20.20,Regular,0.096907,Meat,175.5028,OUT018,2009,Medium,Tier 3,Supermarket Type2,6729.9064
641,FDY51,12.50,Low Fat,0.081465,Meat,220.7798,OUT018,2009,Medium,Tier 3,Supermarket Type2,6611.3940
2282,NCX30,16.70,Low Fat,0.026729,Household,248.4776,OUT018,2009,Medium,Tier 3,Supermarket Type2,6439.6176
2887,FDR25,17.00,Regular,0.140090,Canned,265.1884,OUT018,2009,Medium,Tier 3,Supermarket Type2,6359.7216

- Note that when sorting by multiple columns, pandas sort_value() uses the first variable first and second variable next. 
- We can see the difference by switching the order of column names in the list.

In [51]:
# changed the order of columns
data_BM.sort_values(by=['Item_Outlet_Sales', 'Outlet_Establishment_Year'], ascending=False, inplace=True)
data_BM[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
4888,FDF39,14.850,Regular,0.019495,Dairy,261.2910,OUT013,1987,High,Tier 3,Supermarket Type1,10256.6490
4289,NCM05,6.825,Low Fat,0.059847,Health and Hygiene,262.5226,OUT046,1997,Small,Tier 1,Supermarket Type1,9779.9362
6409,FDA21,13.650,Low Fat,0.035931,Snack Foods,184.4924,OUT013,1987,High,Tier 3,Supermarket Type1,9069.5276
4991,NCQ53,17.600,Low Fat,0.018905,Health and Hygiene,234.6590,OUT046,1997,Small,Tier 1,Supermarket Type1,8508.9240
5752,FDI15,13.800,Low Fat,0.141326,Dairy,265.0884,OUT035,2004,Small,Tier 2,Supermarket Type1,8479.6288

- We can use **sort_index()** to sort pandas dataframe to sort by row index or names. 
- In this example, row index are numbers and in the earlier example we sorted data frame by 'Item_Outlet_Sales', 'Outlet_Establishment_Year' and therefore the row index are jumbled up. 
- We can sort by row index (with inplace=True option) and retrieve the original dataframe.

In [52]:
# sort by index
data_BM.sort_index(inplace=True)
data_BM[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088

### 2. Merging dataframes

- Joining and merging DataFrames is the core process to start with data analysis and machine learning tasks. 
- It is one of the toolkits which every Data Analyst or Data Scientist should master because in almost all the cases data comes from multiple source and files.
- Pandas has two useful functions for merging dataframes:
    - **concat()**
    - **merge()**

In [53]:
#### Creating dummy data
# create dummy data
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])
 

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['C4', 'C5', 'C6', 'C7'],
                     'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])
 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                     'B': ['B8', 'B9', 'B10', 'B11'],
                     'C': ['C8', 'C9', 'C10', 'C11'],
                     'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8, 9, 10, 11])

### a. concat() for combining dataframes
- Suppose you have the following three dataframes: df1, df2 and df3 and you want to combine them **"row-wise"** so that they become a single dataframe like the given image:
- You can use **concat()** here. You will have to pass the names of the DataFrames in a list as the argument to the concat().

In [54]:
# combine dataframes
result = pd.concat([df1, df2, df3])
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

- pandas also provides you with an option to label the DataFrames, after the concatenation, with a key so that you may know which data came from which DataFrame.
- You can achieve the same by passing additional argument **keys** specifying the label names of the DataFrames in a list.

In [55]:
# combine dataframes
result = pd.concat([df1, df2, df3], keys=['x', 'y', 'z'])
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11

- Mentioning the keys also makes it easy to retrieve data corresponding to a particular DataFrame. 
- You can retrieve the data of DataFrame df2 which had the label `y` by using the `loc` method.

In [56]:
# get second dataframe
result.loc['y']

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

- When gluing together multiple DataFrames, you have a choice of how to handle the other axes (other than the one being concatenated). This can be done in the following three ways:

    - Take the union of them all, `join='outer'`. This is the default option as it results in zero information loss.
    - Take the intersection, `join='inner'`.
    - Use a specific index, as passed to the `join_axes` argument.

- Here is an example of each of these methods. First, the default `join='outer'` behavior:

In [57]:
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                        'D': ['D2', 'D3', 'D6', 'D7'],
                        'F': ['F2', 'F3', 'F6', 'F7']},
                       index=[2, 3, 6, 7])
    

result = pd.concat([df1, df4], axis=1, sort=False)
result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

- Here is the same thing with `join='inner'`:

In [58]:
result = pd.concat([df1, df4], axis=1, join='inner')
result

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

- Lastly, suppose we just wanted to `reuse the exact index` from the original DataFrame:

In [59]:
result = pd.concat([df1, df4], axis=1, join_axes=[df1.index])
result

TypeError: concat() got an unexpected keyword argument 'join_axes'

### b. merge() for combining dataframes using SQL like joins

- Another ubiquitous operation related to DataFrames is the merging operation. 
- Two DataFrames might hold different kinds of information about the same entity and linked by some common feature/column.
- We can use **merge()** to combine such dataframes in pandas.

In [60]:

#### Creating dummy data
# create dummy data
df_a = pd.DataFrame({
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']})

df_b = pd.DataFrame({
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']})

df_c = pd.DataFrame({
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]})

Now these are our dataframes:


- Let's start with a basic join, we want to combine `df_a` with `df_c` based on the `subject_id` column.

In [61]:
pd.merge(df_a, df_c, on='subject_id')

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          5     Ayoung   Atiches       16

- Now that we have done a basic join, let's get into **some commmon SQL joins.**


#### Merge with outer join

- “Full outer join produces the set of all records in Table A and Table B, with matching records from both sides where available. If there is no match, the missing side will contain null.”

In [62]:

pd.merge(df_a, df_b, on='subject_id', how='outer')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black
5          6          NaN         NaN         Bran     Balwner
6          7          NaN         NaN        Bryce       Brice
7          8          NaN         NaN        Betty      Btisan

#### Merge with inner join

- “Inner join produces only the set of records that match in both Table A and Table B.”
![](merge_5.png)

In [63]:
pd.merge(df_a, df_b, on='subject_id', how='inner')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

#### Merge with right join

- “Right outer join produces a complete set of records from Table B, with the matching records (where available) in Table A. If there is no match, the left side will contain null.”

![](merge_7.png)

In [64]:
pd.merge(df_a, df_b, on='subject_id', how='right')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black
2          6          NaN         NaN         Bran     Balwner
3          7          NaN         NaN        Bryce       Brice
4          8          NaN         NaN        Betty      Btisan

#### Merge with left join

- “Left outer join produces a complete set of records from Table A, with the matching records (where available) in Table B. If there is no match, the right side will contain null.”
![](merge_6.png)

In [66]:
pd.merge(df_a, df_b, on='subject_id', how='left')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black

### Merge OR Concat : Which to use when?

1. After learning both of the functions in detail, chances are that you might be confused which to use when. 
2. One major difference is that `merge()` is used to combine dataframes on the basis of values of **common columns**. While`concat()` is used to **append dataframes** one below the other (or sideways, depending on whether the axis option is set to 0 or 1).
3. Exact usage depends upon the kind of data you have and analysis you want to perform.